module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_visibility_groups: 0
  breakpoint: 0
  checklistapi: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_direct_save: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_reference_views_select: 0
  erd: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  kint: 0
  link: 0
  material_admin_support: 0
  media: 0
  media_entity_browser: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  search_api: 0
  search_kint: 0
  seo_checklist: 0
  shortcut: 0
  simple_block: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  type_style: 0
  unified_twig_ext: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  material_admin: 0
  relkb: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
